Description: Don't allow network-config
This may add a new wait time for a file that doesn't exist on existing series
so patch it out.

Author: Brett Holman <brett.holman@canonical.com>
Last-Update: 2024-08-02

--- a/cloudinit/sources/DataSourceNoCloud.py
+++ b/cloudinit/sources/DataSourceNoCloud.py
@@ -190,7 +190,7 @@
 
             # This could throw errors, but the user told us to do it
             # so if errors are raised, let them raise
-            md_seed, ud, vd, network = util.read_seeded(seedfrom, timeout=None)
+            md_seed, ud, vd, _ = util.read_seeded(seedfrom, timeout=None)
             LOG.debug("Using seeded cache data from %s", seedfrom)
 
             # Values in the command line override those from the seed
@@ -199,7 +199,6 @@
             )
             mydata["user-data"] = ud
             mydata["vendor-data"] = vd
-            mydata["network-config"] = network
             found.append(seedfrom)
 
         # Now that we have exhausted any other places merge in the defaults
